pub mod zkward {
    pub mod vault {
        pub mod v1 {
            // Generated by build.rs from proto/vault.proto into $OUT_DIR.
            include!(concat!(env!("OUT_DIR"), "/zkward.vault.v1.rs"));
        }
    }
}
