/**
 * Write a Move test that verifies a REAL proof from this circuit on SUI's
 * built-in verifier, and rejects wrong ones.
 *
 *   bun zk/circuits/export-move-test.ts        (after `node build.mjs` and `node test.mjs` in zk/circuits)
 *
 * The test carries its own verifying key, so it stays valid whatever keys a
 * later build produces. It uses DEVELOPMENT keys: it checks the byte
 * encodings and the Move module, not a production setup.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { proofPointsBytes, publicInputsBytes, toHex, verifyingKeyBytes, le32 } from '../prover/hedgePolicySui';

const here = dirname(fileURLToPath(import.meta.url));
const build = (name: string) => join(here, 'build', name);
const vkey = JSON.parse(readFileSync(build('verification_key_dev.json'), 'utf8'));
// Written by `node test.mjs`: an honest proof that already verified off-chain.
const { proof, publicSignals, caps: capsJson } = JSON.parse(readFileSync(build('sample_proof.json'), 'utf8'));
const caps = { leverageCap: BigInt(capsJson.leverageCap), notionalCapCents: BigInt(capsJson.notionalCapCents) };
const commitment = BigInt(publicSignals[0]);
// The module rebuilds the public inputs itself; this checks our own encoding agrees with it.
if (toHex(publicInputsBytes(publicSignals)) !== toHex(le32(commitment)) + toHex(le32(caps.leverageCap)) + toHex(le32(caps.notionalCapCents))) {
  throw new Error('public input encoding mismatch');
}

const VK = toHex(verifyingKeyBytes(vkey));
const PROOF = toHex(proofPointsBytes(proof));
const COMMITMENT = toHex(le32(commitment));

const move = `// GENERATED by zk/circuits/export-move-test.ts. Do not edit by hand.
// A real Groth16 proof from zk/circuits/hedge_policy.circom, made with
// DEVELOPMENT keys, checked by the chain's own verifier.
#[test_only]
module zkvanguard::zk_hedge_policy_tests {
    use sui::test_scenario as ts;
    use zkvanguard::zk_hedge_policy::{Self, PolicyVerifier};

    const SUBMITTER: address = @0xA11CE;
    const LEVERAGE_CAP: u64 = ${caps.leverageCap};
    const NOTIONAL_CAP_CENTS: u64 = ${caps.notionalCapCents};

    const VK: vector<u8> = x"${VK}";
    const PROOF: vector<u8> = x"${PROOF}";
    const COMMITMENT: vector<u8> = x"${COMMITMENT}";

    fun with_verifier(): ts::Scenario {
        let mut scenario = ts::begin(SUBMITTER);
        zk_hedge_policy::create_verifier(VK, scenario.ctx());
        scenario.next_tx(SUBMITTER);
        scenario
    }

    #[test]
    fun a_real_proof_verifies_and_is_recorded() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        assert!(zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS));
        assert!(!zk_hedge_policy::is_attested(&verifier, COMMITMENT));
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        assert!(zk_hedge_policy::is_attested(&verifier, COMMITMENT));
        assert!(zk_hedge_policy::total_attested(&verifier) == 1);
        let (lev, notional) = zk_hedge_policy::attested_caps(&verifier, COMMITMENT);
        assert!(lev == LEVERAGE_CAP && notional == NOTIONAL_CAP_CENTS);
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    fun the_proof_is_rejected_for_lower_caps_and_for_another_commitment() {
        let scenario = with_verifier();
        let verifier = scenario.take_shared<PolicyVerifier>();
        // The hedge has leverage 3: a proof made against cap 4 says nothing under cap 2.
        assert!(!zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, 2, NOTIONAL_CAP_CENTS));
        assert!(!zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, LEVERAGE_CAP, 1));
        let mut other = COMMITMENT;
        let first = other[0];
        *(&mut other[0]) = if (first == 255) 0 else first + 1;
        assert!(!zk_hedge_policy::check(&verifier, PROOF, other, LEVERAGE_CAP, NOTIONAL_CAP_CENTS));
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EProofRejected)]
    fun attesting_under_the_wrong_cap_aborts() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, 2, NOTIONAL_CAP_CENTS, scenario.ctx());
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EAlreadyAttested)]
    fun a_commitment_is_attested_once() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EBadCommitment)]
    fun a_short_commitment_aborts() {
        let scenario = with_verifier();
        let verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::check(&verifier, PROOF, x"00", LEVERAGE_CAP, NOTIONAL_CAP_CENTS);
        ts::return_shared(verifier);
        scenario.end();
    }
}
`;
const out = join(here, '..', '..', 'contracts', 'sui', 'tests', 'zk_hedge_policy_tests.move');
writeFileSync(out, move);
console.log(`wrote ${out}: vk ${VK.length / 2} bytes, proof ${PROOF.length / 2} bytes`);
process.exit(0);
