// GENERATED by zk/circuits/export-move-test.ts. Do not edit by hand.
// A real Groth16 proof from zk/circuits/hedge_policy.circom, made with
// DEVELOPMENT keys, checked by the chain's own verifier.
#[test_only]
module zkvanguard::zk_hedge_policy_tests {
    use sui::test_scenario as ts;
    use zkvanguard::zk_hedge_policy::{Self, PolicyVerifier};

    const SUBMITTER: address = @0xA11CE;
    const LEVERAGE_CAP: u64 = 4;
    const NOTIONAL_CAP_CENTS: u64 = 100000000;

    const VK: vector<u8> = x"dbac39771bcaefca1c1f870c0a7ec3a732bf43815bcf5b4496e3d19c86b757989530223274159bc8df18318f48aca48092c12b3b855a7118b67b31a86a5fdd1b1081b7d702c10ed7a6ad145f345a52bcfeed16439232275b31801402bf062588edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e199e7333b9cc2bd3217b042c9d8f5e6c9bb42798301f2938da63e5815ca216fb16ca2950cec7f94799c2997f6a1e09ba72eb9aa3131175c2f28753a871ac5b2a8a04000000000000000bf42f7066f775f1c8a8ccea83e79d1227dc70109e6a1556ba146a42c1e53582ff15f99722fe7e01516d2286dcb8f0a03116b64c970bad80a6f6ed45fb77632e15b71477feb2104811c10c2418b6fb54bc25a7a22833e331ea762f4e68002a92a64858bc3ad633856d2d5a8ef8d5bde76b5d8e284265ccc0da4e309044977501";
    const PROOF: vector<u8> = x"fe5c453402638c114e801bb88817d41af03e94b3bb2fa0ae7de1d3d1be0ee389fc97f672bc0292fa2a066d136068ec3575ea1cfca005299f1a21098b603794136c60d3b1f79bc7ccb6d03606b426ab3a28b2d3fa558a5646fa0fe47f093efba4ca2ae75bf8d9c5f6bccbae1f1a1071b7dc3e25e26c0065e294d05ce15ac87192";
    const COMMITMENT: vector<u8> = x"f8fde5533479fa34f4ed9e44cf00ac7ba87f47f5e80cb173e15fa12049fca10d";

    fun with_verifier(): ts::Scenario {
        let mut scenario = ts::begin(SUBMITTER);
        zk_hedge_policy::create_verifier(VK, scenario.ctx());
        scenario.next_tx(SUBMITTER);
        scenario
    }

    #[test]
    fun a_real_proof_verifies_and_is_recorded() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        assert!(zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS));
        assert!(!zk_hedge_policy::is_attested(&verifier, COMMITMENT));
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        assert!(zk_hedge_policy::is_attested(&verifier, COMMITMENT));
        assert!(zk_hedge_policy::total_attested(&verifier) == 1);
        let (lev, notional) = zk_hedge_policy::attested_caps(&verifier, COMMITMENT);
        assert!(lev == LEVERAGE_CAP && notional == NOTIONAL_CAP_CENTS);
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    fun the_proof_is_rejected_for_lower_caps_and_for_another_commitment() {
        let scenario = with_verifier();
        let verifier = scenario.take_shared<PolicyVerifier>();
        // The hedge has leverage 3: a proof made against cap 4 says nothing under cap 2.
        assert!(!zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, 2, NOTIONAL_CAP_CENTS));
        assert!(!zk_hedge_policy::check(&verifier, PROOF, COMMITMENT, LEVERAGE_CAP, 1));
        let mut other = COMMITMENT;
        let first = other[0];
        *(&mut other[0]) = if (first == 255) 0 else first + 1;
        assert!(!zk_hedge_policy::check(&verifier, PROOF, other, LEVERAGE_CAP, NOTIONAL_CAP_CENTS));
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EProofRejected)]
    fun attesting_under_the_wrong_cap_aborts() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, 2, NOTIONAL_CAP_CENTS, scenario.ctx());
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EAlreadyAttested)]
    fun a_commitment_is_attested_once() {
        let mut scenario = with_verifier();
        let mut verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        zk_hedge_policy::attest(&mut verifier, PROOF, COMMITMENT, LEVERAGE_CAP, NOTIONAL_CAP_CENTS, scenario.ctx());
        ts::return_shared(verifier);
        scenario.end();
    }

    #[test]
    #[expected_failure(abort_code = zk_hedge_policy::EBadCommitment)]
    fun a_short_commitment_aborts() {
        let scenario = with_verifier();
        let verifier = scenario.take_shared<PolicyVerifier>();
        zk_hedge_policy::check(&verifier, PROOF, x"00", LEVERAGE_CAP, NOTIONAL_CAP_CENTS);
        ts::return_shared(verifier);
        scenario.end();
    }
}
